// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qswjxgjfynphxvobaitl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzd2p4Z2pmeW5waHh2b2JhaXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwMTMwMTIsImV4cCI6MjA4NTU4OTAxMn0.TgPSOkQ33obql08DHfOz01TbTK2L_1ViZE0TDYlZujM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});